### ISSUE TITLE
file train

### ISSUE THREAD

**Issue by butterflyro** [liuh127/NTIRE-2021-Dehazing-DWGAN#2]
can you please provide the train file, i am also working in this direction, thanks if you can help

**Comment by liuh127** [comment]
> can you please provide the train file, i am also working in this direction, thanks if you can help

Hi,

We currently don't have plan to provide training script.
You can refer to our work Two-branch dehaizng, which provides a training script.

**Comment by butterflyro** [comment]
i mean you have predictions on other datasets, but training is on random crop 256x256, so i don't know if prediction just needs to be fit to network input, or needs further processing

**Comment by butterflyro** [comment]
I tested with weights you provided, the results were not the same as in the paper

**Comment by liuh127** [comment]
> I tested with weights you provided, the results were not the same as in the paper

You should train our network on the training split of the dataset you want to test. For example, to test on ITS, you should train our network on RESIDE indoor. There's no guarantee that a single pre-trained model can work on every dehazing datasets. 
BTW, the provided model is just used to produce final results on the testing stage of NTIRE 2021. If you want to have the results as listed in our table for NTIRE20 and NTIRE21, you should re-train our network follows the data split of NTIRE20 and NTIRE21 in our paper.

**Comment by butterflyro** [comment]
sorry for the late reply, did you mean the result of NTIRE2021 is training only on data of NTIRE2020 and NTIRE2021, and let me ask one more question, what is your method of initializing the weights.
