### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Nimbus1997** [liuh127/NTIRE-2021-Dehazing-DWGAN#7]
Hello:)  
First, thank you for making and revealing the amazing dehazing net! 

I am on a way to making a similar dehazing net, and it will be a great help if I can see your training code. Can you please, if possible, disclose train.py as well? 

Thanks for reading my issue! 
hope you have a nice day

**Comment by liuy8106** [comment]
Have you received train.py?If you have received training code,please send to liuy106@stu.xjtu.edu.cn.
Thank you very much!
